### ISSUE TITLE
Calibration Events disappear from Inventory after initial creation

### ISSUE THREAD

**Issue by spetillo** [WHOIGit/ooicgsn-roundabout#147]
Calibration Events that contain all deleted Calibration Names show up in Search, but not in Inventory's Calibration Coefficient History, IF there are no new Calibration Events created with new Calibration Names.

Compare Calibration Coefficient History vs search on the Calibration Inventory for: 
CGINS-CTDMOG-13431 (new & old Events show in CC History tab)
CGINS-CTDMOG-13419 (old events exist, but non show in CC History)
CGINS-CTDMOG-13420 (old events exist, but non show in CC History)

**Comment by spetillo** [comment]
Update: After I navigated away from (and then back to) CGINS-CTDMOG-13431's inventory page, I can no longer see any Calibration Events on that Inventory item, not even the new one I just created.

**Comment by spetillo** [comment]
**UPDATE**: I think this is _partially_ a Staging DB issue with this part. On a part with only new calibration events (e.g., CGINS-CTDBPF-50001, https://ooi-cgrdb-staging.whoi.net/inventory/1089), I can navigate away and back and still see all calibration events, as expected.

So, @MarioCarloni take a look at this, see if you think it's a bug vs only a figment of the broken Staging DB. If you think it's the later, mark it for v1.5.1 instead of v1.5.0 and we'll come back to it later.

**Comment by spetillo** [comment]
@MarioCarloni I was discussing this more with @cahearn, and one option would be to warn the user (when they go to remove a C/C/C Name from a template) that all historical Values for the Name would be purged from the system, and then when they click "OK/Purge" on the warning box, purge those old Name:Value pairs. That could end up causing a lot of trouble, though, if someone does a Name purge without realizing the effects, but we can't hold peoples' hands all the time. I think this would be a reasonable solution that doesn't result in a bunch of removed C/C/C Names hiding our in the database without any way to access them in the UI.

I'm not sure how far you've gotten on this issue already (maybe you already have a fix), but shoot me a Slack message if you would like to discuss implementation updates for this issue and related issue #135 .

**Comment by spetillo** [comment]
From further Slack discussion today:

Mario Carloni:world_map:  3:47 PM
I saw your note on issue #147 as well, regarding the downstream effects of deleting Cal/Const/Conf Names from the Part Template. From any of the Name creation/update forms, I could add a popup warning on-click of the Remove button for any existing row, with a short description of the downstream effects of deletion.

spetillo:national_park:  3:51 PM
That would do

Mario Carloni:world_map:  3:53 PM
Although, I think we could eventually keep all downstream data, like Defaults and actual Constants/Configs/Calibrations, even if the Part Template Name has been removed. This would require significant work, but I think it's doable. (edited) 

spetillo:national_park:  4:05 PM
I don't think we actually want to keep data for Names that have been removed, since that seems fraught with problems down the line.
What about making a way to Deprecate old Names, so options when you click Remove and see the warning would be: Purge, Deprecate, or Cancel? The Purge vs Deprecate options would be briefly explained in the warning message. Deprecate would not allow new assignment of Values to that Name in C/C/C Events, but all pre-existing Name:Value pairs in C/C/C Events would be retained and visible. A Deprecated Name would be marked as Deprecated at the Template level where Names are entered/created, and could no longer be changed. Purge, would do as I previously mentioned. (edited) 

Mario Carloni:world_map:  4:09 PM
I see, so existing Events of any kind, containing Deprecated Names, would retain the Name/Value/Notes pairs as uneditable rows. Purged Names would delete all downstream-associated data. Is that right?

spetillo:national_park:  4:18 PM
Very close... existing Events of any kind, containing Deprecated Names, would retain the Name/Value/Notes pairs, where Value/Notes can be edited (in case there was a typo that someone had to fix), but Name cannot (the Name for a C/C/C is only editable in the Part or Assembly Template anyway).
And, that Deprecated Name cannot have Values/Notes assigned to it in new Events (i.e., you can edit Value/Notes for a Deprecated Name, but you can't add Value/Notes for a Deprecated Name.
For Purge, you're correct.
:+1:

Mario Carloni:world_map:  4:22 PM
I think that makes sense. And fortunately I know exactly where the logic would sit. This shouldn't be an issue to implement. (edited) 
:+1:

**Comment by spetillo** [comment]
I'll add a new ticket for the Deprecation feature so we can get this one ticket closed out after testing today.

**Comment by cahearn** [comment]
Not sure what we're looking for from this issue at this point.  Testing update is that after removing C/C/C names from the PArt Template for PHSEN-E, the Constant and Configuration Records have disappeared from the respective Histories.  Calibration History still has the original Calibration Dates but when clicked they display no records.

Calibration Search and Constant/Configuration Search both returned nothing.  After entering new records, Cal Search worked but Const/Config Search didn't.

I noted other buggy behavior for this part that has me suspicious that some Staging data corruption may be complicating testing here, but have to break off from testing for now.

**Comment by ethanandrews** [comment]
We’ve deployed a fresh copy of the production DB to rdb-testing.whoi.edu if anyone else wants to test outside of the staging data. Your regular logins will work on this site too.


On Aug 31, 2020, at 5:04 PM, cahearn <notifications@github.com> wrote:

﻿

Not sure what we're looking for from this issue at this point. Testing update is that after removing C/C/C names from the PArt Template for PHSEN-E, the Constant and Configuration Records have disappeared from the respective Histories. Calibration History still has the original Calibration Dates but when clicked they display no records.

Calibration Search and Constant/Configuration Search both returned nothing. After entering new records, Cal Search worked but Const/Config Search didn't.

I noted other buggy behavior for this part that has me suspicious that some Staging data corruption may be complicating testing here, but have to break off from testing for now.

**Comment by spetillo** [comment]
@MarioCarloni 
On Staging: 
Now, similar to what @cahearn saw, when I remove a Calibration Name from a Part Template (e.g., I removed cal3 from CTDBP-F Part Template), all Cal Events that contained Values for that Cal Name (e.g., 8/4/20 & 8/30/20 for CGINS-CTDBPF-50001) no longer show that Cal Name/Value/Notes row. If I do a Calibrations Search on that Removed Cal Name (e.g., cal3), it no longer shows up, as if it was purged from the system. This is contrary to what I think you were aiming for: "Calibration Events should now appear in the Inventory Template if they exist, regardless of removed Calibration Names"

![Screenshot from 2020-08-31 16-08-40](https://user-images.githubusercontent.com/11924613/91771092-5c16f000-ebb0-11ea-8af4-0a96af9e8abb.png)

I will try on the Testing server next...

**Comment by MarioCarloni** [comment]
That is expected behavior for now. Calibration Events are the housing for Names and Coefficients. The Deprecation feature will ensure that Names and related data are saved, whose Coefficient Values and Notes remain editable from it's particular Event instance.

**Comment by spetillo** [comment]
Ok, sounds good! Since this is the expected behavior for now (and I think this is logical for the time being), I'm going to call this good as-is. Deprecation will be added with #153 .

I did not get to test on Testing, since I'm out of time today. This is good enough for me for this release, since we have v1.5.1 forthcoming.

@cahearn you mentioned "After entering new records, Cal Search worked but Const/Config Search didn't." If this is still the case, please put in a bug ticket for @sbatchelder for v1.5.1.

**Comment by spetillo** [comment]
@joannekoch For testing: The basic thing to create a functionality test for on this card is that, when a new Calibration Event is _created_, if you navigate away from the Calibration History tab and then back to that tab, it should still show all of the Calibration Names and Values you just entered for that new Calibration Event. 
In addition, we should test that when a Calibration Event is _updated_, all previously existing Name:Value pairs in that Calibration Event are maintained as-is (unless specifically updated) and newly added Name:Value pairs should appear. And (finally), when you navigate away from the Calibration History tab and then back to that tab, as above, all of the updates you made are maintained.
